//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystemWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int OrderId { get; set; }
        public int DrugId { get; set; }
        public int UserID { get; set; }
        public string Drug_Name { get; set; }
        public int Quantity_Ordered { get; set; }
        public decimal Drug_Price { get; set; }
        public System.DateTime Order_Date { get; set; }
    }
}
