//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystemWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int DrugId { get; set; }
        public int UserID { get; set; }
        public string DrugName { get; set; }
        public int QuantityOrdered { get; set; }
        public decimal DrugPrice { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
